CREATE SCHEMA IF NOT EXISTS retail_oi;

-- Destructive owned-source rebuild: discard headers from the prior baseline too.
DROP TABLE IF EXISTS retail_oi.order_header;
DROP TABLE IF EXISTS retail_oi.payment_status_event;
DROP TABLE IF EXISTS retail_oi.shipment_status_event;
DROP TABLE IF EXISTS retail_oi.order_status_event;
DROP TABLE IF EXISTS retail_oi.sales_order_line;
DROP TABLE IF EXISTS retail_oi.product_master;
DROP TABLE IF EXISTS retail_oi.customer_master;
DROP TABLE IF EXISTS retail_oi.source_simulation_run;
DROP TABLE IF EXISTS retail_oi.dq_rejects;
DROP TABLE IF EXISTS retail_oi.watermark_control;
DROP TABLE IF EXISTS retail_oi.number_series;
DROP TABLE IF EXISTS retail_oi.stg_sales_details;
DROP TABLE IF EXISTS retail_oi.stg_px_cat_g1v2;
DROP TABLE IF EXISTS retail_oi.stg_prd_info;
DROP TABLE IF EXISTS retail_oi.stg_loc_a101;
DROP TABLE IF EXISTS retail_oi.stg_cust_az12;
DROP TABLE IF EXISTS retail_oi.stg_cust_info;

CREATE TABLE retail_oi.watermark_control (
    source_table VARCHAR(128) PRIMARY KEY,
    watermark_column VARCHAR(128) NOT NULL,
    last_watermark_val TIMESTAMPTZ(3) NOT NULL,
    dwh_load_ts TIMESTAMPTZ(3) NOT NULL DEFAULT NOW()
);

CREATE TABLE retail_oi.stg_cust_info (
    cst_id INT,
    cst_key VARCHAR(50),
    cst_firstname VARCHAR(100),
    cst_lastname VARCHAR(100),
    cst_marital_status VARCHAR(10),
    cst_gndr VARCHAR(10),
    cst_create_date VARCHAR(20)
);

CREATE TABLE retail_oi.stg_cust_az12 (
    cid VARCHAR(50),
    bdate VARCHAR(20),
    gen VARCHAR(10)
);

CREATE TABLE retail_oi.stg_loc_a101 (
    cid VARCHAR(50),
    cntry VARCHAR(100)
);

CREATE TABLE retail_oi.stg_prd_info (
    prd_id INT,
    prd_key VARCHAR(50),
    prd_nm VARCHAR(200),
    prd_cost NUMERIC(18,2),
    prd_line VARCHAR(20),
    prd_start_dt VARCHAR(20),
    prd_end_dt VARCHAR(20)
);

CREATE TABLE retail_oi.stg_px_cat_g1v2 (
    id VARCHAR(20),
    cat VARCHAR(100),
    subcat VARCHAR(100),
    maintenance VARCHAR(20)
);

CREATE TABLE retail_oi.stg_sales_details (
    sls_ord_num VARCHAR(20),
    sls_prd_key VARCHAR(50),
    sls_cust_id INT,
    sls_order_dt INT,
    sls_ship_dt INT,
    sls_due_dt INT,
    sls_sales NUMERIC(18,2),
    sls_quantity INT,
    sls_price NUMERIC(18,2)
);

CREATE TABLE retail_oi.customer_master (
    customer_key INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT NOT NULL,
    customer_business_key VARCHAR(50),
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    marital_status VARCHAR(10),
    gender VARCHAR(10),
    create_date DATE,
    birth_date DATE,
    country VARCHAR(100),
    state_province VARCHAR(100),
    city VARCHAR(100),
    postal_code VARCHAR(30),
    dwh_load_ts TIMESTAMPTZ(3) NOT NULL DEFAULT NOW(),
    dwh_source_system VARCHAR(20) NOT NULL DEFAULT 'crm'
);

CREATE TABLE retail_oi.product_master (
    product_key INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INT NOT NULL,
    product_business_key VARCHAR(50) NOT NULL,
    product_name VARCHAR(200),
    product_cost NUMERIC(18,2),
    product_line VARCHAR(20),
    start_date DATE,
    end_date DATE,
    category VARCHAR(100),
    subcategory VARCHAR(100),
    maintenance_flag VARCHAR(20),
    dwh_load_ts TIMESTAMPTZ(3) NOT NULL DEFAULT NOW(),
    dwh_source_system VARCHAR(20) NOT NULL DEFAULT 'erp'
);

CREATE TABLE retail_oi.sales_order_line (
    sales_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(20) NOT NULL,
    product_business_key VARCHAR(50) NOT NULL,
    customer_id INT NOT NULL,
    order_date DATE NOT NULL,
    ship_date DATE,
    due_date DATE,
    sales_amount NUMERIC(18,2) NOT NULL,
    quantity INT NOT NULL,
    unit_price NUMERIC(18,2) NOT NULL,
    dwh_load_ts TIMESTAMPTZ(3) NOT NULL DEFAULT NOW(),
    dwh_source_system VARCHAR(20) NOT NULL DEFAULT 'erp'
);

CREATE TABLE retail_oi.order_status_event (
    event_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(20) NOT NULL,
    event_status VARCHAR(30) NOT NULL,
    event_ts TIMESTAMPTZ(3) NOT NULL,
    dwh_load_ts TIMESTAMPTZ(3) NOT NULL DEFAULT NOW(),
    dwh_source_system VARCHAR(20) NOT NULL DEFAULT 'sql'
);

CREATE TABLE retail_oi.shipment_status_event (
    event_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(20) NOT NULL,
    shipment_status VARCHAR(30) NOT NULL,
    event_ts TIMESTAMPTZ(3) NOT NULL,
    dwh_load_ts TIMESTAMPTZ(3) NOT NULL DEFAULT NOW(),
    dwh_source_system VARCHAR(20) NOT NULL DEFAULT 'sql'
);

CREATE TABLE retail_oi.payment_status_event (
    event_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(20) NOT NULL,
    payment_status VARCHAR(30) NOT NULL,
    event_ts TIMESTAMPTZ(3) NOT NULL,
    dwh_load_ts TIMESTAMPTZ(3) NOT NULL DEFAULT NOW(),
    dwh_source_system VARCHAR(20) NOT NULL DEFAULT 'sql'
);

CREATE TABLE retail_oi.dq_rejects (
    dq_reject_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_table VARCHAR(128) NOT NULL,
    source_record_key VARCHAR(200),
    reject_rule VARCHAR(100) NOT NULL,
    reject_reason VARCHAR(4000) NOT NULL,
    reject_severity VARCHAR(20) NOT NULL DEFAULT 'warning',
    source_payload TEXT,
    dwh_batch_id VARCHAR(100),
    dwh_load_ts TIMESTAMPTZ(3) NOT NULL DEFAULT NOW()
);

CREATE TABLE retail_oi.source_simulation_run (
    simulation_run_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_date DATE NOT NULL,
    started_at TIMESTAMPTZ(3) NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ(3),
    new_rows_requested INT NOT NULL,
    existing_update_rows INT NOT NULL,
    late_arriving_rows INT NOT NULL,
    duplicate_rows INT NOT NULL,
    dirty_rate_per_10000 INT NOT NULL,
    event_sample_percent INT NOT NULL,
    rows_inserted INT,
    rows_updated INT,
    order_events_inserted INT,
    shipment_events_inserted INT,
    payment_events_inserted INT,
    run_status VARCHAR(30) NOT NULL DEFAULT 'running',
    error_message VARCHAR(4000),
    dwh_load_ts TIMESTAMPTZ(3) NOT NULL DEFAULT NOW()
);

CREATE TABLE retail_oi.number_series (
    n INT PRIMARY KEY
);

CREATE INDEX ix_customer_master_dwh_load_ts
    ON retail_oi.customer_master (dwh_load_ts);

CREATE INDEX ix_customer_master_postal_code
    ON retail_oi.customer_master (postal_code);

CREATE INDEX ix_product_master_dwh_load_ts
    ON retail_oi.product_master (dwh_load_ts);

CREATE INDEX ix_sales_order_line_dwh_load_ts
    ON retail_oi.sales_order_line (dwh_load_ts);

CREATE INDEX ix_order_status_event_dwh_load_ts
    ON retail_oi.order_status_event (dwh_load_ts);

CREATE INDEX ix_shipment_status_event_dwh_load_ts
    ON retail_oi.shipment_status_event (dwh_load_ts);

CREATE INDEX ix_payment_status_event_dwh_load_ts
    ON retail_oi.payment_status_event (dwh_load_ts);

CREATE INDEX ix_dq_rejects_source_table_load_ts
    ON retail_oi.dq_rejects (source_table, dwh_load_ts);

CREATE INDEX ix_source_simulation_run_date
    ON retail_oi.source_simulation_run (run_date, started_at);
